#!/bin/bash

# basic
sudo cp -a /etc/apt/sources.list{,.bak}
sudo sed -i "s@http://.*archive.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list
sudo sed -i "s@http://.*security.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list
sudo apt update

pkgs=(
    build-essential manpages-dev
    clang-tools clangd
    libssl-dev cmake
    gawk tree
    curl wget
)

sudo apt install -y ${pkgs[@]}
sudo apt dist-upgrade -y

cp -r bin ~
cp -r virtualize/bin ~

(cd shell && bash setup)
(cd vim && bash setup)
