#!/bin/bash

if [ ${UID} -eq 0 ] ;then
    SUDO=
else
    SUDO=sudo
fi

[ -f '/etc/apt/sources.list.bak' ] || ${SUDO} cp -a /etc/apt/sources.list{,.bak}
${SUDO} sed -i "s@http://.*archive.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list
${SUDO} sed -i "s@http://.*security.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list
${SUDO} apt update

basic_debian_pkgs=(
    build-essential manpages-dev
    clang-tools clangd
    libssl-dev gcc g++ make cmake
    dos2unix curl wget nmap tree
)
${SUDO} apt install -y ${basic_debian_pkgs[@]}
${SUDO} apt dist-upgrade -y

(cd shell && bash setup)
(cd vim && bash setup)
