#!/bin/bash
set -e

cat > /dev/null <<EOF
属性名                          含义
ro.build.version.sdk	        SDK 版本
ro.build.version.release	Android 系统版本
ro.build.version.security_patch	Android 安全补丁程序级别
ro.product.model	        型号
ro.product.brand        	品牌
ro.product.name	                设备名
ro.product.board	        处理器型号
ro.product.cpu.abilist	        CPU 支持的 abi 列表[节注一]
persist.sys.isUsbOtgEnabled	是否支持 OTG
dalvik.vm.heapsize	        每个应用程序的内存上限
ro.sf.lcd_density	        屏幕密度
EOF

adb shell getprop
