#!/bin/bash

# https://baike.baidu.com/item/IMEI/1626447?fr=aladdin
raw=($(adb shell service call iphonesubinfo 1 |
while read line
do
        echo $line | egrep '.[0-9].' \
                   | sed -r 's#[0-9a-fA-F]{8}##g' \
                   | awk '{print $2}' \
                   | sed -r "s#\.##g" \
                   | sed $'s/\'//g'
done))
echo ${raw[@]} | sed 's/ //g'
