#!/bin/bash

if [ ${UID} -eq 0 ] ;then
    SUDO=
else
    SUDO=sudo
fi

# login shell
${SUDO} apt install -y zsh tmux

if command -v zsh > /dev/null ;then
    ${SUDO} chsh -s $(grep zsh /etc/shells | head -n1) ${USER}
fi

cp -r bin .shell .bashrc .zshrc .tmux.conf ${HOME}

bash git-setup
