#!/bin/bash

if uname -r | grep -i -q 'wsl' ;then
    echo "Windows WSL kernel detected!"
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo bash get-docker.sh
    sudo service docker start
else
    sudo apt install -y docker.io
    sudo systemctl start docker.io
fi

sudo apt install -y docker-compose

cp -r bin ~
