#!/usr/bin/env bash


port=$1
client=$2

ip=$(ip route get 1.2.3.4 | awk '{print $7;exit 0}')

[ -n "$port" ] || exit 1
[ -n "$ip" ] || exit 2
[ -n "$client" ] || client='demo'

url_root="http://$ip:$port"

# new client specified via key phoneNumber
token_cmd_post=(
        curl
        -X POST
        -H 'Content-Type: application/json'
        -d "{\"username\": \"KunPengPC-TestBot\",
             \"password\": \"bb7ac8477fb997b545ec06b1fcd9c11ad6db9f30d82ca19843941176eec64490\",
             \"phoneNumber\": \"$client\",
             \"operate\": \"get\",
             \"msg\": \"apply for new token\"}"
        $url_root/token
)

"${token_cmd_post[@]}"
echo
